config/routes.rb
Rails.application.routes.draw do
  get 'home/index' , to: 'home#index'

  root 'home#index'
  resources :messages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
    @message = Message.new

  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @messages = Message.all
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/index.html.erb
<div class="home-container center">
    <%= image_tag("Logo.svg", :alt => "Logo") %>
  <%= link_to "Start a chat", messages_url, class: "btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatMmiStuffs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;400;600;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <%= link_to root_path do %>
        <%= image_tag("Logo.svg", :alt => "Logo", :class => "header-logo") %>
      <% end %>

    </header>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.text_field :text, class:'msg-input'%>
  <%= f.button :submit, class:'btn-primary' %>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div class="msg-container">
<p id="notice"><%= notice %></p>

<h1>Messages</h1>
<table>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td class="msg"><%= message.text %><br> <span class="date"><%= message.created_at %></span></td>
        <td class="msg-actions">
          <%= link_to edit_message_path(message), id:"edit" do %>
            <%= fa_icon "pencil"%>
          <% end %>
        </td>
        <td class="msg-actions">
          <%= link_to message, method: :delete, data: { confirm: 'Are you sure?' }, id:"destroy" do %>
            <%= fa_icon "trash"%>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
<br>
<br>
<footer>
<%= render 'form', message: @message %>
</footer>

app/views/messages/new.html.erb
<div class="msg-container">
<p id="notice"><%= notice %></p>

<h1>Messages</h1>
<table>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td class="msg"><%= message.text %><br> <span class="date"><%= message.created_at %></span></td>
        <td class="msg-actions">
          <%= link_to edit_message_path(message), id:"edit" do %>
            <%= fa_icon "pencil"%>
          <% end %>
        </td>
        <td class="msg-actions">
          <%= link_to message, method: :delete, data: { confirm: 'Are you sure?' }, id:"destroy" do %>
            <%= fa_icon "trash"%>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
<br>
<br>
<footer>
<%= render 'form', message: @message %>
</footer>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>